project:
  type: website

website:
  title: "Data Analysis Guides for the Developmental Psychopathology Lab"
  repo-url: https://github.com/DevPsyLab/DataAnalysis
  repo-actions: [edit, source, issue]
  google-analytics: G-TYR0QMREEW
  sidebar:
    style: "floating"
    contents:
      - text: "ABCD Data"
        href: abcdData.qmd
      - text: "Bayesian Analysis"
        href: bayesian.qmd
      - text: "Data Management"
        href: dataManagement.qmd
      - text: "Developmental Scaling"
        href: developmentalScaling.qmd
      - text: "Directed Acyclic Graphs"
        href: dags.qmd
      - text: "Electroencephalography/Event-Related Potentials"
        href: eegERP.qmd
      - text: "Exploratory Data Analysis"
        href: eda.qmd
      - text: "Factor Analysis"
        href: factorAnalysis.qmd
      - text: "Figures"
        href: figures.qmd
      - text: "Git, GitLab, and GitHub"
        href: git.qmd
      - text: "Hierarchical Linear Modeling"
        href: hlm.qmd
      - text: "High-Performance Computing"
        href: hpc.qmd
      - text: "Item Response Theory"
        href: irt.qmd
      - text: "jamovi"
        href: jamovi.qmd
      - text: "JATOS (Just Another Tool for Online Studies)"
        href: jatos.qmd
      - text: "jsPsych"
        href: jsPsych.qmd
      - text: "LAMP (Linux, Apache, MySQL, PHP)"
        href: lamp.qmd
      - text: "Longitudinal Data Analysis"
        href: lda.qmd
      - text: "Markdown"
        href: markdown.qmd
      - text: "Mediation"
        href: sem.qmd#mediation
      - text: "Moderation/Interaction"
        href: regression.qmd#moderation
      - text: "Mplus"
        href: mplus.qmd
      - text: "Multiple Imputation"
        href: multipleImputation.qmd
      - text: "Open Science Framework"
        href: osf.qmd
      - text: "Principal Component Analysis"
        href: pca.qmd
      - text: "Python"
        href: https://devpsylab.github.io/pythonDataAnalysisGuides
      - text: "R"
        href: R.qmd
      - text: "Regression"
        href: regression.qmd
      - text: "SPSS"
        href: SPSS.qmd
      - text: "Statistics"
        href: statistics.qmd
      - text: "Structural Equation Modeling"
        href: sem.qmd
  navbar:
    logo: images/labLogo.png
    search: true
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: https://github.com/DevPsyLab/DataAnalysis
          - text: "Report a Bug"
            href: https://github.com/DevPsyLab/DataAnalysis/issues/new
      - icon: twitter
        href: https://twitter.com/devpsylab
      - icon: facebook
        href: https://www.facebook.com/DevPsyLab
      - icon: instagram
        href: https://www.instagram.com/dev_psy_lab
    left:
      - text: "Datasets"
        menu:
        - text: "ABCD Study Data"
          href: abcdData.qmd
      - text: "Analysis Techniques"
        menu:
        - text: "Bayesian Analysis"
          href: bayesian.qmd
        - text: "Data Management"
          href: dataManagement.qmd
        #- text: "Developmental Scaling"
        #  href: developmentalScaling.qmd
        - text: "Directed Acyclic Graphs"
          href: dags.qmd
        - text: "Electroencephalography/Event-Related Potentials"
          href: eegERP.qmd
        - text: "Exploratory Data Analysis"
          href: eda.qmd
        - text: "Factor Analysis"
          href: factorAnalysis.qmd
        - text: "Figures"
          href: figures.qmd
        - text: "Hierarchical Linear Modeling"
          href: hlm.qmd
        - text: "Item Response Theory"
          href: irt.qmd
        - text: "Longitudinal Data Analysis"
          href: lda.qmd
        - text: "Mediation"
          href: sem.qmd#mediation
        - text: "Moderation/Interaction"
          href: regression.qmd#moderation
        - text: "Multiple Imputation"
          href: multipleImputation.qmd
        - text: "Principal Component Analysis"
          href: pca.qmd
        - text: "Regression"
          href: regression.qmd
        - text: "Statistics"
          href: statistics.qmd
        - text: "Structural Equation Modeling"
          href: sem.qmd
      - text: "Software/Frameworks"
        menu:
        - text: "Git, GitLab, and GitHub"
          href: git.qmd
        - text: "High-Performance Computing Cluster"
          href: hpc.qmd
        - text: "jamovi"
          href: jamovi.qmd
        - text: "JATOS (Just Another Tool for Online Studies)"
          href: jatos.qmd
        - text: "jsPsych"
          href: jsPsych.qmd
        - text: "LAMP (Linux, Apache, MySQL, PHP)"
          href: lamp.qmd
        - text: "Markdown"
          href: markdown.qmd
        - text: "Mplus"
          href: mplus.qmd
        - text: "Open Science Framework"
          href: osf.qmd
        - text: "Python"
          href: https://devpsylab.github.io/pythonDataAnalysisGuides
        - text: "R"
          href: R.qmd
        - text: "SPSS"
          href: SPSS.qmd
      - text: "About"
        href: about.qmd
    right:
    - text: "Lab Wiki"
      href: https://devpsylab.github.io/LabWiki
    - text: "Lab Website"
      href: https://developmental-psychopathology.lab.uiowa.edu

format:
  html:
    highlight-style: a11y
    theme: cosmo
    css: ["styles.css", "includes/custom.css", "font/css/roboto.css"]
    toc: true
    toc-depth: 5
    toc-title: Contents
    toc-location: right
    execute:
      error: true
      warning: false
    code-link: true
    number-sections: true
    code-fold: show
    anchor-sections: true
    df-print: paged
    code-tools:
      source: true
      toggle: true
    link-external-newwindow: true
    #include-in-header:
    #  - "includes/google_analytics.html"
    include-after-body:
      - "includes/footer.html"
    license: CC BY
    author-meta: "Isaac T. Petersen"
    date-meta: today
